#!/usr/bin/env python
import pika, sys, os
import sqlite3
import os
import subprocess

def get_wifi_signal_strength(interface):
    try:
        output = subprocess.check_output(["iwconfig", interface])
        output = output.decode("utf-8")
        signal_line = [line for line in output.split('\n') if "Signal level" in line]
        if signal_line:
            signal_strength = signal_line[0].split("Signal level=")[1].split()[0]
            return signal_strength
        else:
            return "Signal level not found"
    except subprocess.CalledProcessError:
        return "Error retrieving signal strength"

def create_table(cursor):
    cursor.execute('''CREATE TABLE IF NOT EXISTS pdata (
                        time TIMESTAMP DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')),
                        size INTEGER,
                        cpu_usage FLOAT,
                        ram_usage FLOAT,
                        wifi_signal_strength VARCHAR(10)
                    )''')
    
def get_resource_usage(process_id):
    try:
        # Run the 'ps' command to get the CPU and RAM usage for the specified process ID
        command = f"ps -p {process_id} -o %cpu,%mem"
        result = subprocess.check_output(command, shell=True, text=True)
        
        # Extract CPU and RAM values from the result
        lines = result.strip().split('\n')
        cpu_value = float(lines[1].split()[0]) if len(lines) > 1 else None
        ram_value = float(lines[1].split()[1]) if len(lines) > 1 else None
        return cpu_value, ram_value
    except subprocess.CalledProcessError:
        return None, None

def insert_data(cursor, size, process_id):
    cpu_usage, ram_usage = get_resource_usage(process_id)
    wifi_signal_strength = get_wifi_signal_strength("wlan0")
    cursor.execute("INSERT INTO pdata (size, cpu_usage, ram_usage, wifi_signal_strength) VALUES (?, ?, ?, ?)", (size, cpu_usage, ram_usage, wifi_signal_strength))

def main():
    process_id = os.getpid()
    print("Process ID:", process_id)

    credentials = pika.PlainCredentials('qwerty', 'qwerty')
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='broker.local', credentials=credentials))
    channel = connection.channel()

    channel.queue_declare(queue='hello')

    def callback(ch, method, properties, body):
        size = len(body)
        print(f" [x] Received {size} from hello")
        
        conn = sqlite3.connect('amqpp.db')
        cursor = conn.cursor()

        create_table(cursor)
        insert_data(cursor, size, process_id)

        conn.commit()
        conn.close()

    channel.basic_consume(queue='hello', on_message_callback=callback, auto_ack=True)

    print(' [*] Waiting for messages. To exit press CTRL+C')
    channel.start_consuming()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Interrupted')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
